import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import ToasterContext from "./context/ToasterContext";
import AuthContext from "./context/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "pinterest",
  description: "Generated by reem ebrahim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <Header />
          {children}
          <ToasterContext />
        </AuthContext>
      </body>
    </html>
  );
}
